ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  

  # define one master


  (1..4).each do |i|
    config.vm.define "kh-wrk-#{i}-rabbit-cluster" do |node|
      node.vm.provider "virtualbox" do |vbworker|
        vbworker.name = "kh-wrk-#{i}-rabbitmq"
        vbworker.memory = "1024"
        vbworker.cpus = 1
      end
    end
  end
end